apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-productpage
  namespace: student38-bookinfo-dev
  labels:
    app: bookinfo-dev-productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-productpage
  template:
    metadata:
      labels:
        app: bookinfo-dev-productpage
    spec:
      containers:
      - name: bookinfo-dev-productpage
        image: ghcr.io/memorisza/bookinfo-productpage:dev
        imagePullPolicy: Always
        env:
        - name: RATINGS_HOSTNAME
          value: http://sitkmutt.bookinfo.dev.opsta.net/student38/ratings/
        - name: DETAILS_HOSTNAME
          value: http://sitkmutt.bookinfo.dev.opsta.net/student38/details/
        - name: REVIEWS_HOSTNAME
          value: http://sitkmutt.bookinfo.dev.opsta.net/student38/reviews/
      imagePullSecrets:
      - name: registry-bookinfo
